file=open('demo.txt','r')
print(file.read())
file.close()
print()
file=open('demo.txt','w')
file.write('Automation testing')
file.close()
print()
file=open('demo.txt','a')
file.write('\nShakthipriya AK will get 10-14LPA by Jan 2027')
print('demo.txt')
file.close()
print()
file=open('demo.txt','a')
file.write('\nPython\nSelenium')
print(file)
file.close()